# https://apache.github.io/cassandra-java-driver/4.19.0/core/configuration/#configuration
datastax-java-driver {
  advanced.protocol.version = V4
  basic.request {
    default-idempotence = true
    consistency = LOCAL_QUORUM
    serial-consistency = LOCAL_SERIAL
  }
  advanced.reconnection-policy.class = ConstantReconnectionPolicy
  advanced.reconnection-policy.base-delay = 1 second
  advanced.connection {
    pool {
      local.size = 8
      remote.size = 1
    }
    max-requests-per-connection = 4096
  }
  advanced.request.warn-if-set-keyspace = false
  advanced.throttler {
    class = ConcurrencyLimitingRequestThrottler
    max-concurrent-requests = 10000
    max-queue-size = 100000
  }
  advanced.timestamp-generator.class = ServerSideTimestampGenerator
  profiles {
    slow {
      basic.request.timeout = 300 seconds
    }
    collector {
      basic.request.timeout = 30 seconds
    }
    rollup {
      basic.request.timeout = 20 seconds
    }
    web {
      basic.request.timeout = 20 seconds
    }
  }
}