{{- if and .Values.adminDefault.enabled .Values.adminDefault.json }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glowroot-central.fullname" . }}-admin-default
  labels:
    {{- include "glowroot-central.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-default.json: |
{{ .Values.adminDefault.json | indent 4 }}
{{- end }}
