{{- if and (not .Values.cassandra.existingSecret) (or .Values.cassandra.contactPoints .Values.cassandra.symmetricEncryptionKey .Values.cassandra.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glowroot-central.fullname" . }}-cassandra
  labels:
    {{- include "glowroot-central.labels" . | nindent 4 }}
type: Opaque
stringData:
  contactPoints: {{ .Values.cassandra.contactPoints | quote }}
  username: {{ .Values.cassandra.username | quote }}
  password: {{ .Values.cassandra.password | quote }}
  keyspace: {{ .Values.cassandra.keyspace | quote }}
  localDatacenter: {{ .Values.cassandra.localDatacenter | quote }}
  symmetricEncryptionKey: {{ .Values.cassandra.symmetricEncryptionKey | quote }}
{{- end }}
