// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Common.proto

package org.glowroot.agent.it.harness.grpc;

public final class Common {
  private Common() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface VoidOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org_glowroot_agent_it_harness.Void)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org_glowroot_agent_it_harness.Void}
   */
  public  static final class Void extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org_glowroot_agent_it_harness.Void)
      VoidOrBuilder {
    // Use Void.newBuilder() to construct.
    private Void(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Void() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Void(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.it.harness.grpc.Common.internal_static_org_glowroot_agent_it_harness_Void_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.it.harness.grpc.Common.internal_static_org_glowroot_agent_it_harness_Void_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.it.harness.grpc.Common.Void.class, org.glowroot.agent.it.harness.grpc.Common.Void.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.Common.Void parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glowroot.agent.it.harness.grpc.Common.Void prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org_glowroot_agent_it_harness.Void}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org_glowroot_agent_it_harness.Void)
        org.glowroot.agent.it.harness.grpc.Common.VoidOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glowroot.agent.it.harness.grpc.Common.internal_static_org_glowroot_agent_it_harness_Void_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glowroot.agent.it.harness.grpc.Common.internal_static_org_glowroot_agent_it_harness_Void_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glowroot.agent.it.harness.grpc.Common.Void.class, org.glowroot.agent.it.harness.grpc.Common.Void.Builder.class);
      }

      // Construct using org.glowroot.agent.it.harness.grpc.Common.Void.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glowroot.agent.it.harness.grpc.Common.internal_static_org_glowroot_agent_it_harness_Void_descriptor;
      }

      public org.glowroot.agent.it.harness.grpc.Common.Void getDefaultInstanceForType() {
        return org.glowroot.agent.it.harness.grpc.Common.Void.getDefaultInstance();
      }

      public org.glowroot.agent.it.harness.grpc.Common.Void build() {
        org.glowroot.agent.it.harness.grpc.Common.Void result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glowroot.agent.it.harness.grpc.Common.Void buildPartial() {
        org.glowroot.agent.it.harness.grpc.Common.Void result = new org.glowroot.agent.it.harness.grpc.Common.Void(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glowroot.agent.it.harness.grpc.Common.Void) {
          return mergeFrom((org.glowroot.agent.it.harness.grpc.Common.Void)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glowroot.agent.it.harness.grpc.Common.Void other) {
        if (other == org.glowroot.agent.it.harness.grpc.Common.Void.getDefaultInstance()) return this;
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glowroot.agent.it.harness.grpc.Common.Void parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glowroot.agent.it.harness.grpc.Common.Void) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org_glowroot_agent_it_harness.Void)
    }

    // @@protoc_insertion_point(class_scope:org_glowroot_agent_it_harness.Void)
    private static final org.glowroot.agent.it.harness.grpc.Common.Void DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glowroot.agent.it.harness.grpc.Common.Void();
    }

    public static org.glowroot.agent.it.harness.grpc.Common.Void getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Void>
        PARSER = new com.google.protobuf.AbstractParser<Void>() {
      public Void parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new Void(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<Void> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Void> getParserForType() {
      return PARSER;
    }

    public org.glowroot.agent.it.harness.grpc.Common.Void getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glowroot_agent_it_harness_Void_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_glowroot_agent_it_harness_Void_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Common.proto\022\035org_glowroot_agent_it_ha" +
      "rness\"\006\n\004VoidB$\n\"org.glowroot.agent.it.h" +
      "arness.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_glowroot_agent_it_harness_Void_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_glowroot_agent_it_harness_Void_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_glowroot_agent_it_harness_Void_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
