// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConfigUpdateService.proto

package org.glowroot.agent.it.harness.grpc;

public final class ConfigUpdateServiceOuterClass {
  private ConfigUpdateServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface InstrumentationConfigListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org_glowroot_agent_it_harness.InstrumentationConfigList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    java.util.List<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig> 
        getInstrumentationConfigList();
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig getInstrumentationConfig(int index);
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    int getInstrumentationConfigCount();
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    java.util.List<? extends org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder> 
        getInstrumentationConfigOrBuilderList();
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder getInstrumentationConfigOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org_glowroot_agent_it_harness.InstrumentationConfigList}
   */
  public  static final class InstrumentationConfigList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org_glowroot_agent_it_harness.InstrumentationConfigList)
      InstrumentationConfigListOrBuilder {
    // Use InstrumentationConfigList.newBuilder() to construct.
    private InstrumentationConfigList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private InstrumentationConfigList() {
      instrumentationConfig_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private InstrumentationConfigList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                instrumentationConfig_ = new java.util.ArrayList<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig>();
                mutable_bitField0_ |= 0x00000001;
              }
              instrumentationConfig_.add(input.readMessage(org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          instrumentationConfig_ = java.util.Collections.unmodifiableList(instrumentationConfig_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList.class, org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList.Builder.class);
    }

    public static final int INSTRUMENTATION_CONFIG_FIELD_NUMBER = 1;
    private java.util.List<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig> instrumentationConfig_;
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    public java.util.List<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig> getInstrumentationConfigList() {
      return instrumentationConfig_;
    }
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    public java.util.List<? extends org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder> 
        getInstrumentationConfigOrBuilderList() {
      return instrumentationConfig_;
    }
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    public int getInstrumentationConfigCount() {
      return instrumentationConfig_.size();
    }
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    public org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig getInstrumentationConfig(int index) {
      return instrumentationConfig_.get(index);
    }
    /**
     * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
     */
    public org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder getInstrumentationConfigOrBuilder(
        int index) {
      return instrumentationConfig_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < instrumentationConfig_.size(); i++) {
        output.writeMessage(1, instrumentationConfig_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < instrumentationConfig_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, instrumentationConfig_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org_glowroot_agent_it_harness.InstrumentationConfigList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org_glowroot_agent_it_harness.InstrumentationConfigList)
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList.class, org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList.Builder.class);
      }

      // Construct using org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getInstrumentationConfigFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (instrumentationConfigBuilder_ == null) {
          instrumentationConfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          instrumentationConfigBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_descriptor;
      }

      public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList getDefaultInstanceForType() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList.getDefaultInstance();
      }

      public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList build() {
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList buildPartial() {
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList result = new org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList(this);
        int from_bitField0_ = bitField0_;
        if (instrumentationConfigBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            instrumentationConfig_ = java.util.Collections.unmodifiableList(instrumentationConfig_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.instrumentationConfig_ = instrumentationConfig_;
        } else {
          result.instrumentationConfig_ = instrumentationConfigBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList) {
          return mergeFrom((org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList other) {
        if (other == org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList.getDefaultInstance()) return this;
        if (instrumentationConfigBuilder_ == null) {
          if (!other.instrumentationConfig_.isEmpty()) {
            if (instrumentationConfig_.isEmpty()) {
              instrumentationConfig_ = other.instrumentationConfig_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInstrumentationConfigIsMutable();
              instrumentationConfig_.addAll(other.instrumentationConfig_);
            }
            onChanged();
          }
        } else {
          if (!other.instrumentationConfig_.isEmpty()) {
            if (instrumentationConfigBuilder_.isEmpty()) {
              instrumentationConfigBuilder_.dispose();
              instrumentationConfigBuilder_ = null;
              instrumentationConfig_ = other.instrumentationConfig_;
              bitField0_ = (bitField0_ & ~0x00000001);
              instrumentationConfigBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getInstrumentationConfigFieldBuilder() : null;
            } else {
              instrumentationConfigBuilder_.addAllMessages(other.instrumentationConfig_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig> instrumentationConfig_ =
        java.util.Collections.emptyList();
      private void ensureInstrumentationConfigIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          instrumentationConfig_ = new java.util.ArrayList<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig>(instrumentationConfig_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder> instrumentationConfigBuilder_;

      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public java.util.List<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig> getInstrumentationConfigList() {
        if (instrumentationConfigBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instrumentationConfig_);
        } else {
          return instrumentationConfigBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public int getInstrumentationConfigCount() {
        if (instrumentationConfigBuilder_ == null) {
          return instrumentationConfig_.size();
        } else {
          return instrumentationConfigBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig getInstrumentationConfig(int index) {
        if (instrumentationConfigBuilder_ == null) {
          return instrumentationConfig_.get(index);
        } else {
          return instrumentationConfigBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder setInstrumentationConfig(
          int index, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig value) {
        if (instrumentationConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentationConfigIsMutable();
          instrumentationConfig_.set(index, value);
          onChanged();
        } else {
          instrumentationConfigBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder setInstrumentationConfig(
          int index, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder builderForValue) {
        if (instrumentationConfigBuilder_ == null) {
          ensureInstrumentationConfigIsMutable();
          instrumentationConfig_.set(index, builderForValue.build());
          onChanged();
        } else {
          instrumentationConfigBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder addInstrumentationConfig(org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig value) {
        if (instrumentationConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentationConfigIsMutable();
          instrumentationConfig_.add(value);
          onChanged();
        } else {
          instrumentationConfigBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder addInstrumentationConfig(
          int index, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig value) {
        if (instrumentationConfigBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentationConfigIsMutable();
          instrumentationConfig_.add(index, value);
          onChanged();
        } else {
          instrumentationConfigBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder addInstrumentationConfig(
          org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder builderForValue) {
        if (instrumentationConfigBuilder_ == null) {
          ensureInstrumentationConfigIsMutable();
          instrumentationConfig_.add(builderForValue.build());
          onChanged();
        } else {
          instrumentationConfigBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder addInstrumentationConfig(
          int index, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder builderForValue) {
        if (instrumentationConfigBuilder_ == null) {
          ensureInstrumentationConfigIsMutable();
          instrumentationConfig_.add(index, builderForValue.build());
          onChanged();
        } else {
          instrumentationConfigBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder addAllInstrumentationConfig(
          java.lang.Iterable<? extends org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig> values) {
        if (instrumentationConfigBuilder_ == null) {
          ensureInstrumentationConfigIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, instrumentationConfig_);
          onChanged();
        } else {
          instrumentationConfigBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder clearInstrumentationConfig() {
        if (instrumentationConfigBuilder_ == null) {
          instrumentationConfig_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          instrumentationConfigBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public Builder removeInstrumentationConfig(int index) {
        if (instrumentationConfigBuilder_ == null) {
          ensureInstrumentationConfigIsMutable();
          instrumentationConfig_.remove(index);
          onChanged();
        } else {
          instrumentationConfigBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder getInstrumentationConfigBuilder(
          int index) {
        return getInstrumentationConfigFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder getInstrumentationConfigOrBuilder(
          int index) {
        if (instrumentationConfigBuilder_ == null) {
          return instrumentationConfig_.get(index);  } else {
          return instrumentationConfigBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public java.util.List<? extends org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder> 
           getInstrumentationConfigOrBuilderList() {
        if (instrumentationConfigBuilder_ != null) {
          return instrumentationConfigBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instrumentationConfig_);
        }
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder addInstrumentationConfigBuilder() {
        return getInstrumentationConfigFieldBuilder().addBuilder(
            org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder addInstrumentationConfigBuilder(
          int index) {
        return getInstrumentationConfigFieldBuilder().addBuilder(
            index, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.getDefaultInstance());
      }
      /**
       * <code>repeated .org_glowroot_agent_it_harness.InstrumentationConfig instrumentation_config = 1;</code>
       */
      public java.util.List<org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder> 
           getInstrumentationConfigBuilderList() {
        return getInstrumentationConfigFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder> 
          getInstrumentationConfigFieldBuilder() {
        if (instrumentationConfigBuilder_ == null) {
          instrumentationConfigBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfig.Builder, org.glowroot.agent.it.harness.model.ConfigUpdate.InstrumentationConfigOrBuilder>(
                  instrumentationConfig_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          instrumentationConfig_ = null;
        }
        return instrumentationConfigBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org_glowroot_agent_it_harness.InstrumentationConfigList)
    }

    // @@protoc_insertion_point(class_scope:org_glowroot_agent_it_harness.InstrumentationConfigList)
    private static final org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList();
    }

    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstrumentationConfigList>
        PARSER = new com.google.protobuf.AbstractParser<InstrumentationConfigList>() {
      public InstrumentationConfigList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new InstrumentationConfigList(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<InstrumentationConfigList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstrumentationConfigList> getParserForType() {
      return PARSER;
    }

    public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.InstrumentationConfigList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ClassUpdateCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org_glowroot_agent_it_harness.ClassUpdateCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 value = 1;</code>
     */
    int getValue();
  }
  /**
   * Protobuf type {@code org_glowroot_agent_it_harness.ClassUpdateCount}
   */
  public  static final class ClassUpdateCount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org_glowroot_agent_it_harness.ClassUpdateCount)
      ClassUpdateCountOrBuilder {
    // Use ClassUpdateCount.newBuilder() to construct.
    private ClassUpdateCount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ClassUpdateCount() {
      value_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ClassUpdateCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              value_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount.class, org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private int value_;
    /**
     * <code>optional int32 value = 1;</code>
     */
    public int getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (value_ != 0) {
        output.writeInt32(1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (value_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org_glowroot_agent_it_harness.ClassUpdateCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org_glowroot_agent_it_harness.ClassUpdateCount)
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount.class, org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount.Builder.class);
      }

      // Construct using org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_descriptor;
      }

      public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount getDefaultInstanceForType() {
        return org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount.getDefaultInstance();
      }

      public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount build() {
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount buildPartial() {
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount result = new org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount) {
          return mergeFrom((org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount other) {
        if (other == org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount.getDefaultInstance()) return this;
        if (other.getValue() != 0) {
          setValue(other.getValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int value_ ;
      /**
       * <code>optional int32 value = 1;</code>
       */
      public int getValue() {
        return value_;
      }
      /**
       * <code>optional int32 value = 1;</code>
       */
      public Builder setValue(int value) {
        
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org_glowroot_agent_it_harness.ClassUpdateCount)
    }

    // @@protoc_insertion_point(class_scope:org_glowroot_agent_it_harness.ClassUpdateCount)
    private static final org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount();
    }

    public static org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClassUpdateCount>
        PARSER = new com.google.protobuf.AbstractParser<ClassUpdateCount>() {
      public ClassUpdateCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ClassUpdateCount(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ClassUpdateCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClassUpdateCount> getParserForType() {
      return PARSER;
    }

    public org.glowroot.agent.it.harness.grpc.ConfigUpdateServiceOuterClass.ClassUpdateCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031ConfigUpdateService.proto\022\035org_glowroo" +
      "t_agent_it_harness\032\022ConfigUpdate.proto\032\014" +
      "Common.proto\"q\n\031InstrumentationConfigLis" +
      "t\022T\n\026instrumentation_config\030\001 \003(\01324.org_" +
      "glowroot_agent_it_harness.Instrumentatio" +
      "nConfig\"!\n\020ClassUpdateCount\022\r\n\005value\030\001 \001" +
      "(\0052\365\004\n\023ConfigUpdateService\022v\n\027updateTran" +
      "sactionConfig\0226.org_glowroot_agent_it_ha" +
      "rness.TransactionConfigUpdate\032#.org_glow" +
      "root_agent_it_harness.Void\022z\n\031updateUser",
      "RecordingConfig\0228.org_glowroot_agent_it_" +
      "harness.UserRecordingConfigUpdate\032#.org_" +
      "glowroot_agent_it_harness.Void\022p\n\024update" +
      "AdvancedConfig\0223.org_glowroot_agent_it_h" +
      "arness.AdvancedConfigUpdate\032#.org_glowro" +
      "ot_agent_it_harness.Void\022l\n\022updatePlugin" +
      "Config\0221.org_glowroot_agent_it_harness.P" +
      "luginConfigUpdate\032#.org_glowroot_agent_i" +
      "t_harness.Void\022\211\001\n\034updateInstrumentation" +
      "Configs\0228.org_glowroot_agent_it_harness.",
      "InstrumentationConfigList\032/.org_glowroot" +
      "_agent_it_harness.ClassUpdateCountB$\n\"or" +
      "g.glowroot.agent.it.harness.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.glowroot.agent.it.harness.model.ConfigUpdate.getDescriptor(),
          org.glowroot.agent.it.harness.grpc.Common.getDescriptor(),
        }, assigner);
    internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_glowroot_agent_it_harness_InstrumentationConfigList_descriptor,
        new java.lang.String[] { "InstrumentationConfig", });
    internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_glowroot_agent_it_harness_ClassUpdateCount_descriptor,
        new java.lang.String[] { "Value", });
    org.glowroot.agent.it.harness.model.ConfigUpdate.getDescriptor();
    org.glowroot.agent.it.harness.grpc.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
