// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JavaagentService.proto

package org.glowroot.agent.it.harness.grpc;

public final class JavaagentServiceOuterClass {
  private JavaagentServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AppUnderTestClassNameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org_glowroot_agent_it_harness.AppUnderTestClassName)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string value = 1;</code>
     */
    java.lang.String getValue();
    /**
     * <code>optional string value = 1;</code>
     */
    com.google.protobuf.ByteString
        getValueBytes();
  }
  /**
   * Protobuf type {@code org_glowroot_agent_it_harness.AppUnderTestClassName}
   */
  public  static final class AppUnderTestClassName extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org_glowroot_agent_it_harness.AppUnderTestClassName)
      AppUnderTestClassNameOrBuilder {
    // Use AppUnderTestClassName.newBuilder() to construct.
    private AppUnderTestClassName(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private AppUnderTestClassName() {
      value_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private AppUnderTestClassName(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              value_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName.class, org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private volatile java.lang.Object value_;
    /**
     * <code>optional string value = 1;</code>
     */
    public java.lang.String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        value_ = s;
        return s;
      }
    }
    /**
     * <code>optional string value = 1;</code>
     */
    public com.google.protobuf.ByteString
        getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, value_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, value_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org_glowroot_agent_it_harness.AppUnderTestClassName}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org_glowroot_agent_it_harness.AppUnderTestClassName)
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassNameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName.class, org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName.Builder.class);
      }

      // Construct using org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_descriptor;
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName getDefaultInstanceForType() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName.getDefaultInstance();
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName build() {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName buildPartial() {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName result = new org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName) {
          return mergeFrom((org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName other) {
        if (other == org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName.getDefaultInstance()) return this;
        if (!other.getValue().isEmpty()) {
          value_ = other.value_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object value_ = "";
      /**
       * <code>optional string value = 1;</code>
       */
      public java.lang.String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public com.google.protobuf.ByteString
          getValueBytes() {
        java.lang.Object ref = value_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          value_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder setValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      /**
       * <code>optional string value = 1;</code>
       */
      public Builder setValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        value_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org_glowroot_agent_it_harness.AppUnderTestClassName)
    }

    // @@protoc_insertion_point(class_scope:org_glowroot_agent_it_harness.AppUnderTestClassName)
    private static final org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName();
    }

    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AppUnderTestClassName>
        PARSER = new com.google.protobuf.AbstractParser<AppUnderTestClassName>() {
      public AppUnderTestClassName parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new AppUnderTestClassName(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<AppUnderTestClassName> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AppUnderTestClassName> getParserForType() {
      return PARSER;
    }

    public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.AppUnderTestClassName getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ExpectedLogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org_glowroot_agent_it_harness.ExpectedLogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string logger_name = 1;</code>
     */
    java.lang.String getLoggerName();
    /**
     * <code>optional string logger_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getLoggerNameBytes();

    /**
     * <code>optional string partial_message = 2;</code>
     */
    java.lang.String getPartialMessage();
    /**
     * <code>optional string partial_message = 2;</code>
     */
    com.google.protobuf.ByteString
        getPartialMessageBytes();
  }
  /**
   * Protobuf type {@code org_glowroot_agent_it_harness.ExpectedLogMessage}
   */
  public  static final class ExpectedLogMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org_glowroot_agent_it_harness.ExpectedLogMessage)
      ExpectedLogMessageOrBuilder {
    // Use ExpectedLogMessage.newBuilder() to construct.
    private ExpectedLogMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ExpectedLogMessage() {
      loggerName_ = "";
      partialMessage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ExpectedLogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              String s = input.readStringRequireUtf8();

              loggerName_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              partialMessage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage.class, org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage.Builder.class);
    }

    public static final int LOGGER_NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object loggerName_;
    /**
     * <code>optional string logger_name = 1;</code>
     */
    public java.lang.String getLoggerName() {
      java.lang.Object ref = loggerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loggerName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string logger_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getLoggerNameBytes() {
      java.lang.Object ref = loggerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loggerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARTIAL_MESSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object partialMessage_;
    /**
     * <code>optional string partial_message = 2;</code>
     */
    public java.lang.String getPartialMessage() {
      java.lang.Object ref = partialMessage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        partialMessage_ = s;
        return s;
      }
    }
    /**
     * <code>optional string partial_message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPartialMessageBytes() {
      java.lang.Object ref = partialMessage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        partialMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getLoggerNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, loggerName_);
      }
      if (!getPartialMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, partialMessage_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getLoggerNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, loggerName_);
      }
      if (!getPartialMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, partialMessage_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org_glowroot_agent_it_harness.ExpectedLogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org_glowroot_agent_it_harness.ExpectedLogMessage)
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage.class, org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage.Builder.class);
      }

      // Construct using org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        loggerName_ = "";

        partialMessage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_descriptor;
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage getDefaultInstanceForType() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage.getDefaultInstance();
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage build() {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage buildPartial() {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage result = new org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage(this);
        result.loggerName_ = loggerName_;
        result.partialMessage_ = partialMessage_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage) {
          return mergeFrom((org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage other) {
        if (other == org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage.getDefaultInstance()) return this;
        if (!other.getLoggerName().isEmpty()) {
          loggerName_ = other.loggerName_;
          onChanged();
        }
        if (!other.getPartialMessage().isEmpty()) {
          partialMessage_ = other.partialMessage_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object loggerName_ = "";
      /**
       * <code>optional string logger_name = 1;</code>
       */
      public java.lang.String getLoggerName() {
        java.lang.Object ref = loggerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          loggerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string logger_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getLoggerNameBytes() {
        java.lang.Object ref = loggerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loggerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string logger_name = 1;</code>
       */
      public Builder setLoggerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        loggerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string logger_name = 1;</code>
       */
      public Builder clearLoggerName() {
        
        loggerName_ = getDefaultInstance().getLoggerName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string logger_name = 1;</code>
       */
      public Builder setLoggerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        loggerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object partialMessage_ = "";
      /**
       * <code>optional string partial_message = 2;</code>
       */
      public java.lang.String getPartialMessage() {
        java.lang.Object ref = partialMessage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          partialMessage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string partial_message = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPartialMessageBytes() {
        java.lang.Object ref = partialMessage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          partialMessage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string partial_message = 2;</code>
       */
      public Builder setPartialMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        partialMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string partial_message = 2;</code>
       */
      public Builder clearPartialMessage() {
        
        partialMessage_ = getDefaultInstance().getPartialMessage();
        onChanged();
        return this;
      }
      /**
       * <code>optional string partial_message = 2;</code>
       */
      public Builder setPartialMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        partialMessage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org_glowroot_agent_it_harness.ExpectedLogMessage)
    }

    // @@protoc_insertion_point(class_scope:org_glowroot_agent_it_harness.ExpectedLogMessage)
    private static final org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage();
    }

    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ExpectedLogMessage>
        PARSER = new com.google.protobuf.AbstractParser<ExpectedLogMessage>() {
      public ExpectedLogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ExpectedLogMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ExpectedLogMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ExpectedLogMessage> getParserForType() {
      return PARSER;
    }

    public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.ExpectedLogMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org_glowroot_agent_it_harness.LogCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 unexpectedCount = 1;</code>
     */
    int getUnexpectedCount();

    /**
     * <code>optional int32 expectedButNotLoggedCount = 2;</code>
     */
    int getExpectedButNotLoggedCount();
  }
  /**
   * Protobuf type {@code org_glowroot_agent_it_harness.LogCount}
   */
  public  static final class LogCount extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org_glowroot_agent_it_harness.LogCount)
      LogCountOrBuilder {
    // Use LogCount.newBuilder() to construct.
    private LogCount(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LogCount() {
      unexpectedCount_ = 0;
      expectedButNotLoggedCount_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              unexpectedCount_ = input.readInt32();
              break;
            }
            case 16: {

              expectedButNotLoggedCount_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_LogCount_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_LogCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount.class, org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount.Builder.class);
    }

    public static final int UNEXPECTEDCOUNT_FIELD_NUMBER = 1;
    private int unexpectedCount_;
    /**
     * <code>optional int32 unexpectedCount = 1;</code>
     */
    public int getUnexpectedCount() {
      return unexpectedCount_;
    }

    public static final int EXPECTEDBUTNOTLOGGEDCOUNT_FIELD_NUMBER = 2;
    private int expectedButNotLoggedCount_;
    /**
     * <code>optional int32 expectedButNotLoggedCount = 2;</code>
     */
    public int getExpectedButNotLoggedCount() {
      return expectedButNotLoggedCount_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (unexpectedCount_ != 0) {
        output.writeInt32(1, unexpectedCount_);
      }
      if (expectedButNotLoggedCount_ != 0) {
        output.writeInt32(2, expectedButNotLoggedCount_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (unexpectedCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, unexpectedCount_);
      }
      if (expectedButNotLoggedCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, expectedButNotLoggedCount_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org_glowroot_agent_it_harness.LogCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org_glowroot_agent_it_harness.LogCount)
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_LogCount_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_LogCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount.class, org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount.Builder.class);
      }

      // Construct using org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        unexpectedCount_ = 0;

        expectedButNotLoggedCount_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.internal_static_org_glowroot_agent_it_harness_LogCount_descriptor;
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount getDefaultInstanceForType() {
        return org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount.getDefaultInstance();
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount build() {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount buildPartial() {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount result = new org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount(this);
        result.unexpectedCount_ = unexpectedCount_;
        result.expectedButNotLoggedCount_ = expectedButNotLoggedCount_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount) {
          return mergeFrom((org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount other) {
        if (other == org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount.getDefaultInstance()) return this;
        if (other.getUnexpectedCount() != 0) {
          setUnexpectedCount(other.getUnexpectedCount());
        }
        if (other.getExpectedButNotLoggedCount() != 0) {
          setExpectedButNotLoggedCount(other.getExpectedButNotLoggedCount());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int unexpectedCount_ ;
      /**
       * <code>optional int32 unexpectedCount = 1;</code>
       */
      public int getUnexpectedCount() {
        return unexpectedCount_;
      }
      /**
       * <code>optional int32 unexpectedCount = 1;</code>
       */
      public Builder setUnexpectedCount(int value) {
        
        unexpectedCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 unexpectedCount = 1;</code>
       */
      public Builder clearUnexpectedCount() {
        
        unexpectedCount_ = 0;
        onChanged();
        return this;
      }

      private int expectedButNotLoggedCount_ ;
      /**
       * <code>optional int32 expectedButNotLoggedCount = 2;</code>
       */
      public int getExpectedButNotLoggedCount() {
        return expectedButNotLoggedCount_;
      }
      /**
       * <code>optional int32 expectedButNotLoggedCount = 2;</code>
       */
      public Builder setExpectedButNotLoggedCount(int value) {
        
        expectedButNotLoggedCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 expectedButNotLoggedCount = 2;</code>
       */
      public Builder clearExpectedButNotLoggedCount() {
        
        expectedButNotLoggedCount_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org_glowroot_agent_it_harness.LogCount)
    }

    // @@protoc_insertion_point(class_scope:org_glowroot_agent_it_harness.LogCount)
    private static final org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount();
    }

    public static org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogCount>
        PARSER = new com.google.protobuf.AbstractParser<LogCount>() {
      public LogCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new LogCount(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<LogCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogCount> getParserForType() {
      return PARSER;
    }

    public org.glowroot.agent.it.harness.grpc.JavaagentServiceOuterClass.LogCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_glowroot_agent_it_harness_LogCount_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_glowroot_agent_it_harness_LogCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026JavaagentService.proto\022\035org_glowroot_a" +
      "gent_it_harness\032\014Common.proto\"&\n\025AppUnde" +
      "rTestClassName\022\r\n\005value\030\001 \001(\t\"B\n\022Expecte" +
      "dLogMessage\022\023\n\013logger_name\030\001 \001(\t\022\027\n\017part" +
      "ial_message\030\002 \001(\t\"F\n\010LogCount\022\027\n\017unexpec" +
      "tedCount\030\001 \001(\005\022!\n\031expectedButNotLoggedCo" +
      "unt\030\002 \001(\0052\376\005\n\020JavaagentService\022P\n\004ping\022#" +
      ".org_glowroot_agent_it_harness.Void\032#.or" +
      "g_glowroot_agent_it_harness.Void\022g\n\nexec" +
      "uteApp\0224.org_glowroot_agent_it_harness.A",
      "ppUnderTestClassName\032#.org_glowroot_agen" +
      "t_it_harness.Void\022X\n\014interruptApp\022#.org_" +
      "glowroot_agent_it_harness.Void\032#.org_glo" +
      "wroot_agent_it_harness.Void\022o\n\025addExpect" +
      "edLogMessage\0221.org_glowroot_agent_it_har" +
      "ness.ExpectedLogMessage\032#.org_glowroot_a" +
      "gent_it_harness.Void\022`\n\020clearLogMessages" +
      "\022#.org_glowroot_agent_it_harness.Void\032\'." +
      "org_glowroot_agent_it_harness.LogCount\022Z" +
      "\n\016resetAllConfig\022#.org_glowroot_agent_it",
      "_harness.Void\032#.org_glowroot_agent_it_ha" +
      "rness.Void\022T\n\010shutdown\022#.org_glowroot_ag" +
      "ent_it_harness.Void\032#.org_glowroot_agent" +
      "_it_harness.Void\022P\n\004kill\022#.org_glowroot_" +
      "agent_it_harness.Void\032#.org_glowroot_age" +
      "nt_it_harness.VoidB$\n\"org.glowroot.agent" +
      ".it.harness.grpcb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.glowroot.agent.it.harness.grpc.Common.getDescriptor(),
        }, assigner);
    internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_glowroot_agent_it_harness_AppUnderTestClassName_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_glowroot_agent_it_harness_ExpectedLogMessage_descriptor,
        new java.lang.String[] { "LoggerName", "PartialMessage", });
    internal_static_org_glowroot_agent_it_harness_LogCount_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_glowroot_agent_it_harness_LogCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_glowroot_agent_it_harness_LogCount_descriptor,
        new java.lang.String[] { "UnexpectedCount", "ExpectedButNotLoggedCount", });
    org.glowroot.agent.it.harness.grpc.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
