spring.rabbitmq.host=${SPRING_RABBITMQ_HOST:localhost}
spring.datasource.url=jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
server.port=8080
logging.level.root=INFO
